[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/tauri-apps/tao?rev=ba65486abe14f2963e016731520e0cdadce3e199"]
git = "https://github.com/tauri-apps/tao"
rev = "ba65486abe14f2963e016731520e0cdadce3e199"
replace-with = "vendored-sources"

[source."git+https://github.com/tauri-apps/wry?rev=2c1c87424053210018015f3898e8e6b0e5bdaa1c"]
git = "https://github.com/tauri-apps/wry"
rev = "2c1c87424053210018015f3898e8e6b0e5bdaa1c"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
